language: python

services:
  - postgresql
  
addons:
  postgresql: "9.4"

python:
  - "3.5"

sudo: false
env:
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py35-djangomaster
  - TOXENV=py36-django111
  - TOXENV=py36-djangomaster

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36-django111
    - python: "3.6"
      env: TOXENV=py36-djangomaster
  exclude:
    - python: "3.5"
      env: TOXENV=py36-django111
    - python: "3.5"
      env: TOXENV=py36-djangomaster

  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install coveralls tox
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - tox
  
after_script:
  - coveralls

notifications:
  email: false
