# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 16:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_bouncer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerACL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(max_length=64)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acls', related_query_name='acl', to='api_bouncer.Consumer')),
            ],
        ),
        migrations.AlterField(
            model_name='api',
            name='hosts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(regex='(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\\.)+[a-zA-Z]{2,63}\\.?$)')]), size=None, validators=[django.core.validators.MinLengthValidator(1, message='At least one is required')]),
        ),
        migrations.AlterField(
            model_name='consumerkey',
            name='key',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterUniqueTogether(
            name='consumeracl',
            unique_together=set([('consumer', 'group')]),
        ),
    ]
